get_genome:
  database: "ncbi"
  assembly: "GCF_000006945.2"
  fasta: Null
  gff: Null

design_guides:
  target_region:  ["NC_003277.2"]
  tss_window:  [0, 500]
  circular:  False
  canonical:  True
  strands:  "both"
  spacer_length:  20
  guide_aligner:  "biostrings"
  crispr_enzyme:  "SpCas9"
  gc_content_range:  [30, 70]
  score_methods:  ["ruleset1", "ruleset3", "crisprater", "crisprscan", "tssdist", "genrich"]
  score_weights:  [1, 1, 1, 1, 1, 1]
  restriction_sites:  Null
  bad_seeds:  ["ACCCA", "ATACT", "TGGAA"]
  filter_top_n:  10
  filter_score_threshold:  Null
  filter_multi_targets: True
  fiveprime_linker: "AAAA"
  threeprime_linker: "GGGG"

visualize_guides:
  show_examples: 20
